spring.application.name=LocalHelpApplication

# Railway DB connection
spring.datasource.url=jdbc:mysql://yamanote.proxy.rlwy.net:10436/railway
spring.datasource.username=root
spring.datasource.password=hFSCrQTiaMQBsWxMLFxhWQaqrGZnTdWY

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Server port
server.port=8080
